CREATE DATABASE surf_spot_db;

CREATE TABLE countries (
    code CHAR(2) PRIMARY KEY NOT NULL,
    name TEXT NOT NULL
);

INSERT INTO countries (code, name) VALUES
    ('AU', 'Australia'),
    ('US', 'United States'),
    ('BR', 'Brazil'),
    ('FR', 'France'),
    ('PT', 'Portugal'),
    ('ID', 'Indonesia'),
    ('ZA', 'South Africa'),
    ('ES', 'Spain'),
    ('MA', 'Morocco'),
    ('MX', 'Mexico'),
    ('CR', 'Costa Rica'),
    ('PE', 'Peru'),
    ('CL', 'Chile'),
    ('NZ', 'New Zealand'),
    ('JP', 'Japan'),
    ('PH', 'Philippines'),
    ('LK', 'Sri Lanka'),
    ('IE', 'Ireland'),
    ('GB', 'United Kingdom'),
    ('NO', 'Norway'),
    ('IS', 'Iceland'),
    ('FJ', 'Fiji'),
    ('PF', 'French Polynesia'),
    ('MV', 'Maldives'),
    ('PA', 'Panama'),
    ('NI', 'Nicaragua'),
    ('SV', 'El Salvador'),
    ('EC', 'Ecuador'),
    ('AR', 'Argentina'),
    ('UY', 'Uruguay'),
    ('CA', 'Canada'),
    ('IT', 'Italy'),
    ('HR', 'Croatia'),
    ('GR', 'Greece'),
    ('TR', 'Turkey'),
    ('IL', 'Israel'),
    ('SN', 'Senegal'),
    ('GH', 'Ghana'),
    ('NA', 'Namibia'),
    ('RE', 'Réunion'),
    ('MU', 'Mauritius'),
    ('TW', 'Taiwan'),
    ('KR', 'South Korea'),
    ('VN', 'Vietnam'),
    ('TH', 'Thailand'),
    ('IN', 'India'),
    ('BB', 'Barbados'),
    ('DO', 'Dominican Republic'),
    ('PR', 'Puerto Rico'),
    ('JM', 'Jamaica');

CREATE TABLE surfing_schools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

INSERT INTO surfing_schools (id, name)
VALUES
    (1, 'Jamie O''Brien Surf Experience'),
    (2, 'Tahiti Surf School'),
    (3, 'Bali Surf Class'),
    (4, 'J-Bay Surf Academy'),
    (5, 'Torquay Surfing Academy'),
    (6, 'Nazaré Water Fun'),
    (7, 'Hossegor Surf Club');

CREATE TABLE coasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    country_code CHAR(2) NOT NULL,

    CONSTRAINT fk_country
    FOREIGN KEY (country_code)
    REFERENCES countries(code)
);

INSERT INTO coasts (id, name, country_code)
VALUES
    (1, 'North Shore', 'US'),
    (2, 'Tahiti Iti', 'PF'),
    (3, 'Bukit Peninsula', 'ID'),
    (4, 'Eastern Cape', 'ZA'),
    (5, 'Surf Coast', 'AU'),
    (6, 'Silver Coast', 'PT'),
    (7, 'Nouvelle-Aquitaine', 'FR');

CREATE TABLE instructors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    surfing_school_id BIGINT,

    CONSTRAINT fk_surfing_school
    FOREIGN KEY (surfing_school_id)
    REFERENCES surfing_schools(id)
);

INSERT INTO instructors (id, first_name, last_name, surfing_school_id)
VALUES
    (1, 'Jamie', 'O''Brien', 1),
    (2, 'Matahi', 'Drollet', 2),
    (3, 'Wayan', 'Suputra', 3),
    (4, 'Cheron', 'Kraak', 4),
    (5, 'Cahill', 'Bell-Warren', 5),
    (6, 'Garrett', 'McNamara', 6),
    (7, 'Joan', 'Duru', 7);

CREATE TABLE surf_spots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    latitude DECIMAL(9, 6) NOT NULL,
    longitude DECIMAL(9, 6) NOT NULL,
    coast_id BIGINT NOT NULL,
    wave_type TEXT NOT NULL,
    wave_height DECIMAL,
    difficulty TEXT,
    wind_direction INT
        CHECK ( wind_direction >= 0 AND wind_direction < 360),
    image_path VARCHAR(255),

    CONSTRAINT fk_coast
    FOREIGN KEY (coast_id)
    REFERENCES coasts(id)
);

INSERT INTO surf_spots (id, name, latitude, longitude, coast_id, wave_type, wave_height, difficulty, wind_direction)
VALUES
    (1, 'Pipeline', 21.6640, -158.0539,  1, 'REEF_BREAK', 5.0, 'EXPERT', 90),
    (2, 'Teahupoo', -17.8470, -149.2670, 2, 'REEF_BREAK', 6.5, 'EXPERT', 45),
    (3, 'Uluwatu', -8.8149, 115.0884, 3, 'REEF_BREAK', 3.0, 'ADVANCED', 135),
    (4, 'Jeffreys Bay', -34.0333, 24.9167,  4, 'POINT_BREAK', 3.5, 'ADVANCED', 270),
    (5, 'Bells Beach', -38.3670, 144.2830, 5, 'POINT_BREAK', 4.0, 'ADVANCED', 315),
    (6, 'Nazare', 39.6010, -9.0830,  6, 'BEACH_BREAK', 24.0, 'EXPERT', 90),
    (7, 'Hossegor', 43.6667, -1.4333, 7, 'BEACH_BREAK', 2.5, 'INTERMEDIATE', 90);

CREATE TABLE surf_spot_months (
    surf_spot_id BIGINT NOT NULL,
    month_name TEXT NOT NULL,

    PRIMARY KEY (surf_spot_id, month_name),

    CONSTRAINT fk_surf_spot
    FOREIGN KEY (surf_spot_id)
    REFERENCES surf_spots(id)
    ON DELETE CASCADE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    username TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL
);

INSERT INTO users (id, username, email, password_hash) VALUES
    (1, 'admin', 'admin','admin_password_hash');

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name TEXT NOT NULL
);

INSERT INTO roles (id, name) VALUES
    (1, 'ADMIN'),
    (2, 'USER');

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    PRIMARY KEY (user_id, role_id),

    CONSTRAINT  fk_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE,

    CONSTRAINT fk_role
    FOREIGN KEY (role_id)
    REFERENCES roles(id)
    ON DELETE CASCADE
);

INSERT INTO user_roles (user_id, role_id) VALUES (1, 1);

CREATE TABLE role_permissions (
    role_id BIGINT,
    permission_name  VARCHAR(50),

    PRIMARY KEY (role_id, permission_name),

    CONSTRAINT fk_role
    FOREIGN KEY (role_id)
    REFERENCES roles(id)
    ON DELETE CASCADE
);

INSERT INTO role_permissions (role_id, permission_name) VALUES
    (1, 'SURF_SPOT_CREATE'),
    (1, 'SURF_SPOT_VIEW'),
    (1, 'SURF_SPOT_MODIFY'),
    (1, 'SURF_SPOT_DELETE'),
    (1, 'MANAGE_USERS');

-- Postavljanje ID generatora na najveci postavljeni ID + 1
SELECT setval(pg_get_serial_sequence('users', 'id'), coalesce(max(id), 1)) FROM users;
SELECT setval(pg_get_serial_sequence('roles', 'id'), coalesce(max(id), 1)) FROM roles;
SELECT setval(pg_get_serial_sequence('surf_spots', 'id'), coalesce(max(id), 1)) FROM surf_spots;
SELECT setval(pg_get_serial_sequence('coasts', 'id'), coalesce(max(id), 1)) FROM coasts;
SELECT setval(pg_get_serial_sequence('instructors', 'id'), coalesce(max(id), 1)) FROM instructors;
SELECT setval(pg_get_serial_sequence('surfing_schools', 'id'), coalesce(max(id), 1)) FROM surfing_schools;