CREATE TABLE countries
(
    code CHAR(2) PRIMARY KEY NOT NULL,
    name TEXT                NOT NULL
);

CREATE TABLE surfing_schools
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE coasts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT    NOT NULL,
    country_code CHAR(2) NOT NULL,

    CONSTRAINT fk_country
        FOREIGN KEY (country_code)
            REFERENCES countries (code)
);

CREATE TABLE instructors
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name        TEXT NOT NULL,
    last_name         TEXT NOT NULL,
    surfing_school_id BIGINT,

    CONSTRAINT fk_surfing_school
        FOREIGN KEY (surfing_school_id)
            REFERENCES surfing_schools (id)
);

CREATE TABLE surf_spots
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT          NOT NULL,
    latitude       DECIMAL(9, 6) NOT NULL,
    longitude      DECIMAL(9, 6) NOT NULL,
    coast_id       BIGINT        NOT NULL,
    wave_type      TEXT          NOT NULL,
    wave_height    DECIMAL,
    difficulty     TEXT,
    wind_direction INT
        CHECK ( wind_direction >= 0 AND wind_direction < 360),
    image_path     VARCHAR(255),

    CONSTRAINT fk_coast
        FOREIGN KEY (coast_id)
            REFERENCES coasts (id)
);

CREATE TABLE surf_spot_schools
(
    surf_spot_id  BIGINT NOT NULL,
    school_id BIGINT NOT NULL,
    PRIMARY KEY (surf_spot_id, school_id),
    FOREIGN KEY (surf_spot_id) REFERENCES surf_spots (id) ON DELETE CASCADE,
    FOREIGN KEY (school_id) REFERENCES surfing_schools (id) ON DELETE CASCADE
);

CREATE TABLE surf_spot_months
(
    surf_spot_id BIGINT NOT NULL,
    month_name   TEXT   NOT NULL,
    PRIMARY KEY (surf_spot_id, month_name),

    CONSTRAINT fk_surf_spot
        FOREIGN KEY (surf_spot_id)
            REFERENCES surf_spots (id) ON DELETE CASCADE
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT        NOT NULL,
    email         TEXT UNIQUE NOT NULL,
    password_hash TEXT        NOT NULL
);

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_role
        FOREIGN KEY (role_id)
            REFERENCES roles (id)
            ON DELETE CASCADE
);

CREATE TABLE role_permissions
(
    role_id         BIGINT,
    permission_name VARCHAR(50),
    PRIMARY KEY (role_id, permission_name),

    CONSTRAINT fk_role
        FOREIGN KEY (role_id)
            REFERENCES roles (id)
            ON DELETE CASCADE
);